[theme]
primaryColor = "#a67c52"
backgroundColor = "#faf6f0"
secondaryBackgroundColor = "#ede4d6"
textColor = "#1f1810"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableStaticServing = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[client]
showErrorDetails = false
toolbarMode = "minimal"
